planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0

  RRTstar:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: true

  PRMstar:
    type: geometric::PRMstar

  EST:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05

  KPIECE:
    type: geometric::KPIECE
    range: 0.0

diana_arm:
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRMstar
    - EST
    - KPIECE

  longest_valid_segment_fraction: 0.005
